/* main.js — AquaBridge Chile SpA */

const T = {
  en: {
    nav_home:"Home", nav_services:"Services", nav_about:"About", nav_contact:"Contact",
    home_pre:"Soft Landing Partner · Chile Market Entry",
    home_h1:"The fastest path from global product to Chilean market.",
    home_sub:"AquaBridge is a soft landing company: we give international aquaculture technology companies a senior local team, C-suite relationships, and commercial execution in Chile from day one. Not an agency. Not a distributor. A committed partner who makes Chile work.",
    home_cta1:"Start the conversation", home_cta2:"How we work",
    stat1_n:"70+", stat1_l:"Years combined experience",
    stat2_n:"USD 6.4B", stat2_l:"Chilean salmon export market",
    stat3_n:"300+", stat3_l:"Active farm centers in Patagonia",
    stat4_n:"35%", stat4_l:"Peak market share built from zero",
    prob_label:"The challenge",
    prob_h2:"Getting Chile right is harder than it looks.",
    prob_sub:"International aquaculture technology companies entering Chile face a predictable set of barriers. Without local relationships, regulatory fluency, and cultural knowledge, the gap between a good product and a Chilean sale can take two years and cost more than you expect.",
    prob_c1_h:"No local relationships", prob_c1_p:"Without trusted introductions, it is nearly impossible to get meetings with decision-makers at Chile's major producers.",
    prob_c2_h:"Regulatory complexity", prob_c2_p:"Regulatory, certification, and tax processes can delay market entry by months without local expertise.",
    prob_c3_h:"Cultural and commercial gap", prob_c3_p:"Commercial norms, negotiation dynamics, and business culture in Chile differ significantly from North America or Northern Europe. AquaBridge bridges that gap directly, with partners who have operated inside the Chilean industry for decades.",
    wwd_label:"Our services",
    wwd_h2:"What AquaBridge does.",
    wwd_sub:"AquaBridge is the only commercial partner built specifically for the Chilean salmon sector. We combine local leadership, decades of direct C-suite relationships with Chile's major producers, and active market facilitation from first introduction to signed agreement. We represent your product, build the commercial relationship, and provide the access and intelligence that make the difference between a product that gains traction and one that does not.",
    wwd_c1_h:"Market entry and facilitation", wwd_c1_p:"We identify the right buyers, arrange the right introductions, and manage the commercial relationship on your behalf from first contact to confirmed sale.",
    wwd_c2_h:"Relationship management", wwd_c2_p:"Our partners have direct, personal relationships with the technology decision-makers at Chile's major salmon producers. We activate those relationships for you.",
    wwd_c3_h:"Market intelligence and advisory", wwd_c3_p:"We tell you honestly how your product is positioned, which pain points it addresses, and what the realistic price point and competitive landscape looks like.",
    howwe_label:"How we work",
    howwe_h2:"How we establish your presence in Chile.",
    howwe_sub:"A focused, four-stage process from market entry to established commercial presence.",
    step1_h:"Assess", step1_p:"Market fit, competitive landscape, regulatory requirements, and realistic entry conditions. You know exactly what you are walking into.",
    step2_h:"Position", step2_p:"Define your commercial approach, pricing, and how you enter the conversation with Chilean producers.",
    step3_h:"Introduce", step3_p:"Senior, direct access to the right decision-makers. We open doors that take years to open alone.",
    step4_h:"Establish", step4_p:"Ongoing relationship management, commercial facilitation, and market presence. Chile becomes part of your business.",
    mkt_label:"The market",
    mkt_h2:"The Chilean salmon sector.",
    mkt_sub:"The world's second-largest farmed salmon producer. A technology adoption environment that rewards the companies that get there first with the right support.",
    mkt_s1_n:"USD 6.37B", mkt_s1_l:"Salmon exports in 2024",
    mkt_s2_n:"1,035,618", mkt_s2_l:"Tonnes exported to 83 countries",
    mkt_s3_n:"USD 30B+", mkt_s3_l:"Projected global market value by 2030",
    mkt_s4_n:"300+", mkt_s4_l:"Active farm centers in Patagonia",
    vs_label:"Why AquaBridge",
    vs_h2:"The right way to enter this market.",
    vs_sub:"Two conventional alternatives are available to international companies entering Chile. Both have significant limitations.",
    vs_col1_head:"Alternative",
    vs_col1_label:"Hiring local staff",
    vs_col1_i1:"Takes 6–12 months to hire and onboard",
    vs_col1_i2:"New hire builds relationships from zero",
    vs_col1_i3:"High fixed cost regardless of sales outcomes",
    vs_col1_i4:"No existing producer network on Day 1",
    vs_col2_head:"Our approach",
    vs_col2_label:"AquaBridge",
    vs_col2_i1:"Senior network activated from Day 1",
    vs_col2_i2:"Direct C-suite access to all major producers",
    vs_col2_i3:"Retainer plus commission: costs align with results",
    vs_col2_i4:"Built specifically for the Chilean salmon sector",
    vs_col3_head:"Alternative",
    vs_col3_label:"Using a distributor",
    vs_col3_i1:"Divided loyalty across multiple product lines",
    vs_col3_i2:"Margin dilution on every transaction",
    vs_col3_i3:"Limited transparency into buyer relationships",
    vs_col3_i4:"Incentive to move volume, not optimise fit",
    team_label:"The team",
    team_h2:"Three partners. Seven decades of combined experience.",
    team_sub:"AquaBridge was built from three senior professionals who have spent careers inside the Chilean and global aquaculture industry.",
    team_link:"Learn more about the team →",
    p1_name:"Javier Infante", p1_role:"Technical Director", p1_bio:"Aquaculture engineer and MBA with 20+ years of international experience.",
    p1_d1:"Principal Investigator, ARPA-E MARINER at Ocean Rainforest Inc.", p1_d2:"Co-founder, SWD Connectors",
    p2_name:"Juan Pablo Barrales", p2_role:"Commercial Director", p2_bio:"25+ years of commercial leadership in the Chilean salmon sector.",
    p2_d1:"Former MD Innovasea Chile: 30–33% YoY growth, 35% market share", p2_d2:"SalmonChile Board Member 2021–2025",
    p3_name:"Jaime Uribe", p3_role:"Legal & Compliance Director", p3_bio:"25+ years in finance, legal administration and regulatory compliance.",
    p3_d1:"Former LATAM Legal Representative, Pentair", p3_d2:"KPMG background. MBA Tax Planning + Master's Compliance",
    cta_h2:"Planning to enter Chile?",
    cta_p:"Let us tell you honestly whether your product is ready for this market, and who the right first customers would be.",
    cta_btn:"Start the conversation",
    footer_tag:"Global connectivity for the aquaculture industry.",
    footer_copy:"© 2026 AquaBridge Chile SpA. All rights reserved.",
    svc_pre:"Engagement structure",
    svc_h1:"Two ways to work with AquaBridge.",
    svc_sub:"Whether you are testing the market for the first time or ready to commit to a full commercial program, we have an engagement structure that fits where you are.",
    exp_badge:"Explorer", exp_h3:"Explorer Engagement", exp_sub:"Market validation before commitment.",
    exp_price:"USD 3,000/month · 3 to 6 months",
    exp_i1:"Market intelligence: product fit, competitive position, regulatory requirements",
    exp_i2:"Initial commercial meetings with pre-qualified producer contacts",
    exp_i3:"Regulatory requirements assessment for import and certification",
    exp_i4:"Go or no-go recommendation with specific first-customer identification",
    exp_i5:"Monthly written activity report",
    acc_badge:"Market Access", acc_h3:"Market Access Program", acc_sub:"Full commercial facilitation.",
    acc_price:"USD 7,000/month retainer + 10% commission on confirmed sales",
    acc_i1:"Active commercial facilitation: direct engagement with buyer decision-makers",
    acc_i2:"Brand positioning and market presence management",
    acc_i3:"Full relationship management across all major producer contacts",
    acc_i4:"Regulatory and compliance advisory",
    acc_i5:"Monthly reporting: pipeline status, meeting notes, next steps",
    acc_i6:"Negotiation support and commercial documentation review",
    svc_note:"Reasonable documented expenses are reimbursed at cost, typically capped at USD 2,000/month. All physical and operational costs are managed directly by the client.",
    no_label:"What we do not do",
    no_h2:"Our focus makes us more effective.",
    no_sub:"AquaBridge does not hold inventory, manage warehouses, conduct field demonstrations, or handle import clearance. We advise on regulatory requirements; clients execute compliance directly. For company formation, accounting, and local administrative setup, we work with trusted local partners and can make introductions on request.",
    no_1:"Inventory holding or warehouse management",
    no_2:"Field demonstrations (managed by the client or their designated technical partner)",
    no_3:"Logistics coordination or import clearance execution",
    no_4:"Distributor functions: we do not resell and do not take title to goods",
    no_note:"This is not a limitation. Staying focused on commercial facilitation and relationship management is what makes us effective.",
    about_pre:"The company",
    about_h1:"Four partners. One shared commitment.",
    about_sub:"AquaBridge Chile SpA was constituted in March 2026, bringing together four professionals with complementary expertise across aquaculture technology, commercial leadership, legal and financial management, and international business development.",
    model_h2:"A pure connector model.",
    model_p1:"AquaBridge does not distribute, resell, or hold inventory. We facilitate introductions and commercial relationships between international technology companies and Chilean salmon producers. We earn a monthly retainer and a 10% commission on confirmed sales.",
    model_p2:"This structure keeps us commercially aligned with our clients' success. Our fees grow when their revenues grow. There is no incentive for us to extend an engagement beyond the point where value is being created.",
    about_team_h2:"The partners.",
    p1_long:"Javier Infante is an aquaculture engineer and MBA with more than 20 years of international experience in aquaculture technology and business development. He serves as Principal Investigator at Ocean Rainforest Inc. under the US Department of Energy's ARPA-E MARINER program, focused on offshore macroalgae cultivation systems. He is co-founder of SWD Connectors. Javier brings the technical credibility and international scientific network that positions AquaBridge as a peer among aquaculture technology companies globally.",
    p2_long:"Juan Pablo Barrales has spent more than 25 years in commercial leadership roles within Chile's salmon sector. As Managing Director of Innovasea Chile, he built the company from zero to a 35% market share, achieving 30 to 33% year-on-year growth. He served on the SalmonChile Board from 2021 to 2025 and has direct relationships with senior decision-makers at Camanchaca, Cermaq, Multiexport, Blumar, and Fjord Seafood, among others. Juan Pablo's network is the foundation of AquaBridge's buyer-side access.",
    p3_long:"Jaime Uribe brings more than 25 years of experience in finance, legal administration, and regulatory compliance. With a Big Four background at KPMG and an MBA in Tax Planning, he served as LATAM Legal Representative for Pentair and as Finance and Administration Manager at Innovasea Chile. He holds a Master's degree in Compliance. Jaime oversees all client communications, legal structures, and compliance matters for AquaBridge engagements.",
    p4_name:"Svein Arve Tronsgård", p4_role:"Business Development Advisor",
    p4_long:"Svein Arve Tronsgård is a business development professional based in Norway, with a background in finance and international commercial development. He is Business Development Director at OXZO S.A and holds a degree from Trondheim Business School. Svein brings a European market perspective and an extensive network in the Norwegian aquaculture and technology sector, supporting AquaBridge's international business development and serving as the primary bridge to the Norwegian and broader European market.",
    contact_pre:"Get in touch",
    contact_h1:"Let's start a conversation.",
    contact_sub:"If you have a technology product and want to understand whether Chile is the right market, we will give you an honest assessment. No commitment required.",
    form_name:"Full name", form_co:"Company", form_country:"Country", form_email:"Email address",
    form_sit:"What best describes your situation?",
    sit_1:"We are evaluating Chile as a potential market",
    sit_2:"We have a product ready and want to start now",
    sit_3:"We have an existing Chile presence that is underperforming",
    sit_4:"We are looking for a local partner or network",
    form_msg:"Message", form_send:"Send message",
    ci_name:"Jaime Uribe", ci_role:"Primary contact",
    ci_email_lbl:"Email", ci_base_lbl:"Base", ci_base:"Puerto Varas, Chile",
  },
  no: {
    nav_home:"Hjem", nav_services:"Tjenester", nav_about:"Om oss", nav_contact:"Kontakt",
    home_pre:"Soft Landing Partner · Markedsinngang i Chile",
    home_h1:"Den raskeste veien fra globalt produkt til det chilenske markedet.",
    home_sub:"AquaBridge er et soft landing-selskap: vi gir internasjonale havbruksteknologiselskaper et seniort lokalt team, relasjoner på toppledernivå og kommersiell gjennomføring i Chile fra dag én. Ikke et byrå. Ikke en distributør. En dedikert partner som får Chile til å fungere.",
    home_cta1:"Ta kontakt", home_cta2:"Slik jobber vi",
    stat1_n:"70+", stat1_l:"Års samlet erfaring",
    stat2_n:"USD 6,4 mrd", stat2_l:"Chilensk lakseksportmarked",
    stat3_n:"300+", stat3_l:"Aktive oppdrettsanlegg i Patagonia",
    stat4_n:"35%", stat4_l:"Markedsandel bygget fra null",
    prob_label:"Utfordringen",
    prob_h2:"Å lykkes i Chile er vanskeligere enn det ser ut.",
    prob_sub:"Internasjonale havbruksteknologiselskaper som skal inn i Chile møter en forutsigbar rekke av barrierer. Uten lokale relasjoner, regulatorisk kunnskap og kulturell forståelse kan veien fra et godt produkt til et chilensk salg ta to år og koste mer enn forventet.",
    prob_c1_h:"Ingen lokale relasjoner", prob_c1_p:"Uten pålitelige introduksjoner er det nesten umulig å få møter med beslutningstakere hos de store produsentene.",
    prob_c2_h:"Regulatorisk kompleksitet", prob_c2_p:"Regulatoriske, sertifiserings- og skatteprosesser kan forsinke markedsinngangen med flere måneder uten lokal ekspertise.",
    prob_c3_h:"Kulturelt og kommersielt gap", prob_c3_p:"Kommersielle normer, forhandlingsdynamikk og forretningskultur i Chile avviker vesentlig fra det man kjenner fra Nord-Amerika eller Nord-Europa. AquaBridge bygger bro over dette gapet direkte, med partnere som har operert inne i den chilenske næringen i tiår.",
    wwd_label:"Våre tjenester",
    wwd_h2:"Hva AquaBridge gjør.",
    wwd_sub:"AquaBridge er den eneste kommersielle partneren bygget spesifikt for den chilenske laksesektoren. Vi kombinerer lokalt lederskap, tiår med direkte relasjoner på toppledernivå hos Chiles største produsenter, og aktiv markedstilrettelegging fra første introduksjon til signert avtale. Vi representerer ditt produkt, bygger det kommersielle forholdet og leverer tilgangen og innsikten som utgjør forskjellen.",
    wwd_c1_h:"Markedsinngang og tilrettelegging", wwd_c1_p:"Vi identifiserer de riktige kjøperne, arrangerer de riktige introduksjonene og håndterer det kommersielle forholdet på dine vegne.",
    wwd_c2_h:"Relasjonhåndtering", wwd_c2_p:"Våre partnere har direkte, personlige relasjoner til teknologibeslutningstagerne hos Chiles største lakseprodusenter. Vi aktiverer disse relasjonene for deg.",
    wwd_c3_h:"Markedsintelligens og rådgivning", wwd_c3_p:"Vi forteller deg ærlig hvordan produktet ditt er posisjonert, hvilke smertepunkter det adresserer, og hva det realistiske prisnivået ser ut.",
    howwe_label:"Slik jobber vi",
    howwe_h2:"Slik etablerer vi din tilstedeværelse i Chile.",
    howwe_sub:"En fokusert, firefasemodell fra markedsinngang til etablert kommersiell tilstedeværelse.",
    step1_h:"Kartlegging", step1_p:"Markedsfit, konkurranselandskap, regulatoriske krav og realistiske inngangsbetingelser. Du vet nøyaktig hva du går inn i.",
    step2_h:"Posisjonering", step2_p:"Vi definerer din kommersielle tilnærming, prissetting og hvordan du best entrer samtalen med chilenske produsenter.",
    step3_h:"Introduksjoner", step3_p:"Direkte tilgang på seniornivå til de rette beslutningstakerne. Vi åpner dører som tar år å åpne alene.",
    step4_h:"Etablering", step4_p:"Løpende relasjonhåndtering, kommersiell tilrettelegging og markedstilstedeværelse. Chile blir en del av din virksomhet.",
    mkt_label:"Markedet",
    mkt_h2:"Den chilenske laksesektoren.",
    mkt_sub:"Verdens nest største oppdrettslakseprodusent. Et marked som belønner selskaper som kommer til riktig tid med riktig støtte.",
    mkt_s1_n:"USD 6,37 mrd", mkt_s1_l:"Lakseksport i 2024",
    mkt_s2_n:"1 035 618", mkt_s2_l:"Tonn eksportert til 83 land",
    mkt_s3_n:"USD 30 mrd+", mkt_s3_l:"Forventet global markedsverdi innen 2030",
    mkt_s4_n:"300+", mkt_s4_l:"Aktive oppdrettsanlegg i Patagonia",
    vs_label:"Hvorfor AquaBridge",
    vs_h2:"Den riktige måten å entre dette markedet på.",
    vs_sub:"To konvensjonelle alternativer er tilgjengelige for internasjonale selskaper som skal inn i Chile. Begge har vesentlige begrensninger.",
    vs_col1_head:"Alternativ",
    vs_col1_label:"Ansette lokalt personell",
    vs_col1_i1:"Tar 6–12 måneder å rekruttere og onboarde",
    vs_col1_i2:"Nyansatt bygger relasjoner fra null",
    vs_col1_i3:"Høy fast kostnad uavhengig av salgsresultater",
    vs_col1_i4:"Ingen eksisterende produsentnettverk fra dag én",
    vs_col2_head:"Vår tilnærming",
    vs_col2_label:"AquaBridge",
    vs_col2_i1:"Seniornettverket aktivert fra dag én",
    vs_col2_i2:"Direkte tilgang på toppledernivå til alle store produsenter",
    vs_col2_i3:"Retainer pluss provisjon: kostnader justeres med resultater",
    vs_col2_i4:"Bygget spesifikt for den chilenske laksesektoren",
    vs_col3_head:"Alternativ",
    vs_col3_label:"Bruke en distributør",
    vs_col3_i1:"Delt lojalitet på tvers av flere produktlinjer",
    vs_col3_i2:"Marginreduksjon på hver transaksjon",
    vs_col3_i3:"Begrenset innsyn i kjøperrelasjoner",
    vs_col3_i4:"Incentiv til å selge volum, ikke optimalisere produktfit",
    team_label:"Teamet",
    team_h2:"Tre partnere. Syv tiår med samlet erfaring.",
    team_sub:"AquaBridge ble bygget av tre seniorfagfolk som har tilbrakt karrierene sine i den chilenske og globale havbruksinæringen.",
    team_link:"Les mer om teamet →",
    p1_name:"Javier Infante", p1_role:"Teknisk direktør", p1_bio:"Havbruksingeniør og MBA med 20+ års internasjonal erfaring.",
    p1_d1:"Principal Investigator, ARPA-E MARINER ved Ocean Rainforest Inc.", p1_d2:"Medgründer, SWD Connectors",
    p2_name:"Juan Pablo Barrales", p2_role:"Kommersiell direktør", p2_bio:"25+ års kommersiell ledelse i den chilenske laksesektoren.",
    p2_d1:"Tidligere ADM Innovasea Chile: 30–33% YoY-vekst, 35% markedsandel", p2_d2:"SalmonChile-styremedlem 2021–2025",
    p3_name:"Jaime Uribe", p3_role:"Juridisk direktør og compliance", p3_bio:"25+ års erfaring innen finans, juridisk administrasjon og etterlevelse.",
    p3_d1:"Tidligere LATAM juridisk representant, Pentair", p3_d2:"KPMG-bakgrunn. MBA Skatteplanlegging + Master i Compliance",
    cta_h2:"Planlegger du å entre Chile?",
    cta_p:"La oss fortelle deg ærlig om produktet ditt er klart for dette markedet, og hvem de riktige førstegangskjøperne vil være.",
    cta_btn:"Ta kontakt",
    footer_tag:"Global tilkobling for havbruksinæringen.",
    footer_copy:"© 2026 AquaBridge Chile SpA. Alle rettigheter forbeholdt.",
    svc_pre:"Engasjementsstruktur",
    svc_h1:"To måter å samarbeide med AquaBridge på.",
    svc_sub:"Enten du tester markedet for første gang eller er klar til å satse på et fullstendig kommersielt program, har vi en engasjementsstruktur som passer.",
    exp_badge:"Explorer", exp_h3:"Explorer-engasjement", exp_sub:"Markedsvalidering før forpliktelse.",
    exp_price:"USD 3 000/mnd · 3 til 6 måneder",
    exp_i1:"Markedsrapport: produktets fit, konkurranseposisjon og regulatoriske krav",
    exp_i2:"Innledende kommersielle møter med forhåndskvalifiserte produsentkontakter",
    exp_i3:"Vurdering av regulatoriske krav for import og sertifisering",
    exp_i4:"Gå/ikke-gå-anbefaling med identifikasjon av spesifikke førstekunder",
    exp_i5:"Månedlig skriftlig aktivitetsrapport",
    acc_badge:"Markedsadgang", acc_h3:"Markedsadgangsprogram", acc_sub:"Full kommersiell tilrettelegging.",
    acc_price:"USD 7 000/mnd retainer + 10% provisjon på bekreftede salg",
    acc_i1:"Aktiv kommersiell tilrettelegging: direkte engasjement med kjøpers beslutningstakere",
    acc_i2:"Merkevareposisjonering og markedstilstedeværelse",
    acc_i3:"Full relasjonhåndtering overfor alle store produsentkontakter",
    acc_i4:"Regulatorisk og compliance-rådgivning",
    acc_i5:"Månedlig rapportering: pipeline-status, møtenotater, neste steg",
    acc_i6:"Forhandlingsstøtte og gjennomgang av kommersiell dokumentasjon",
    svc_note:"Rimelige dokumenterte utgifter refunderes til kostpris, vanligvis begrenset til USD 2 000/mnd. Alle fysiske og operasjonelle kostnader håndteres direkte av klienten.",
    no_label:"Hva vi ikke gjør",
    no_h2:"Vårt fokus gjør oss mer effektive.",
    no_sub:"AquaBridge holder ikke varelager, drifter ikke lagre, gjennomfører ikke feltdemonstrasjoner og håndterer ikke importklarering. Vi rådgir om regulatoriske krav; klienter utfører compliance direkte. For selskapsopprettelse, regnskap og lokal administrativ oppsett samarbeider vi med pålitelige lokale partnere og kan gjøre introduksjoner på forespørsel.",
    no_1:"Lagerbeholdning eller lagerdrift",
    no_2:"Feltdemonstrasjoner (håndteres av klienten eller utpekt teknisk partner)",
    no_3:"Logistikk-koordinering eller utførelse av importklarering",
    no_4:"Distributørfunksjoner: vi er ikke en videreselger og tar ikke eierskap til varer",
    no_note:"Å holde fokus på kommersiell tilrettelegging og relasjonhåndtering er det som gjør oss effektive.",
    about_pre:"Selskapet",
    about_h1:"Fire partnere. Én felles forpliktelse.",
    about_sub:"AquaBridge Chile SpA ble stiftet i mars 2026 og samler fire fagfolk med komplementær ekspertise innen havbruksteknologi, kommersiell ledelse, juridisk og finansiell forvaltning og internasjonal forretningsutvikling.",
    model_h2:"En ren tilkoblingsmodell.",
    model_p1:"AquaBridge distribuerer ikke, videreselger ikke og holder ikke varelager. Vi tilrettelegger introduksjoner og kommersielle relasjoner mellom internasjonale teknologiselskaper og chilenske lakseprodusenter. Vi tjener en månedlig retainer og 10% provisjon på bekreftede salg.",
    model_p2:"Denne strukturen holder oss kommersielt justert med klientenes suksess. Honorærene våre vokser når inntektene deres vokser. Det er ingen incentiver for oss til å forlenge et engasjement utover det punktet der verdi skapes.",
    about_team_h2:"Partnerne.",
    p1_long:"Javier Infante er havbruksingeniør og MBA med mer enn 20 års internasjonal erfaring innen havbruksteknologi og forretningsutvikling. Han er Principal Investigator ved Ocean Rainforest Inc. under det amerikanske energidepartementets ARPA-E MARINER-program, med fokus på offshore makroalgedyrkingssystemer. Han er medgründer av SWD Connectors. Javier bringer den tekniske troverdigheten og det internasjonale vitenskapelige nettverket som posisjonerer AquaBridge som en fagfelle blant havbruksteknologiselskaper globalt.",
    p2_long:"Juan Pablo Barrales har tilbrakt mer enn 25 år i kommersielle lederstillinger i den chilenske laksesektoren. Som administrerende direktør for Innovasea Chile bygde han selskapet fra null til 35% markedsandel med 30 til 33% år-over-år-vekst. Han satt i SalmonChiles styre fra 2021 til 2025 og har direkte relasjoner til seniorbeslutningstagere ved Camanchaca, Cermaq, Multiexport, Blumar og Fjord Seafood, blant andre.",
    p3_long:"Jaime Uribe bringer mer enn 25 års erfaring innen finans, juridisk administrasjon og regulatorisk etterlevelse. Med Big Four-bakgrunn fra KPMG og en MBA i skatteplanlegging tjenestegjorde han som LATAMs juridiske representant for Pentair og som finans- og administrasjonssjef ved Innovasea Chile. Han holder en mastergrad i Compliance.",
    p4_name:"Svein Arve Tronsgård", p4_role:"Rådgiver for forretningsutvikling",
    p4_long:"Svein Arve Tronsgård er en forretningsutviklingsprofesjonell basert i Norge, med bakgrunn innen finans og internasjonal kommersiell utvikling. Han er Business Development Director i OXZO S.A og er utdannet fra Trondheim Økonomiske Høgskole. Svein bringer et europeisk markedsperspektiv og et bredt nettverk i norsk havbruks- og teknologisektor, og støtter AquaBridges internasjonale forretningsutvikling som primær bro til det norske og bredere europeiske markedet.",
    contact_pre:"Ta kontakt",
    contact_h1:"La oss starte en samtale.",
    contact_sub:"Hvis du har et teknologiprodukt og ønsker å forstå om Chile er det rette markedet, gir vi deg en ærlig vurdering. Ingen forpliktelse kreves.",
    form_name:"Fullt navn", form_co:"Selskap", form_country:"Land", form_email:"E-postadresse",
    form_sit:"Hva beskriver best din situasjon?",
    sit_1:"Vi vurderer Chile som et potensielt marked",
    sit_2:"Vi har et produkt klart og ønsker å starte nå",
    sit_3:"Vi har en eksisterende Chile-tilstedeværelse som underpresterer",
    sit_4:"Vi ser etter en lokal partner eller nettverk",
    form_msg:"Melding", form_send:"Send melding",
    ci_name:"Jaime Uribe", ci_role:"Primær kontakt",
    ci_email_lbl:"E-post", ci_base_lbl:"Beliggenhet", ci_base:"Puerto Varas, Chile",
  }
};

function applyLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const k = el.dataset.i18n;
    if (T[lang] && T[lang][k] !== undefined) el.textContent = T[lang][k];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const k = el.dataset.i18nPh;
    if (T[lang] && T[lang][k] !== undefined) el.placeholder = T[lang][k];
  });
  document.querySelectorAll('[data-i18n-opt]').forEach(el => {
    const keys = el.dataset.i18nOpt.split(',');
    el.querySelectorAll('option[data-key]').forEach((opt, i) => {
      const k = opt.dataset.key;
      if (T[lang] && T[lang][k] !== undefined) opt.textContent = T[lang][k];
    });
  });
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  localStorage.setItem('ab_lang', lang);
  document.documentElement.lang = lang === 'no' ? 'no' : 'en';
}

function initNav() {
  const ham = document.querySelector('.nav-hamburger');
  const mob = document.querySelector('.nav-mobile');
  if (ham && mob) {
    ham.addEventListener('click', () => mob.classList.toggle('open'));
  }
  window.addEventListener('scroll', () => {
    document.querySelector('.nav')?.classList.toggle('scrolled', scrollY > 16);
  });
  const page = location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('.nav-links a, .nav-mobile a').forEach(a => {
    const h = a.getAttribute('href') || '';
    if (h === page || (!page || page === 'index.html') && (h === 'index.html' || h === './')) {
      a.classList.add('active');
    }
  });
}

document.addEventListener('DOMContentLoaded', () => {
  initNav();
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => applyLang(btn.dataset.lang));
  });
  applyLang(localStorage.getItem('ab_lang') || 'en');
});
